services:
  publicsos.ro:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WWWUSER: '${WWWUSER:-1000}'
        WWWGROUP: '${WWWGROUP:-1000}'
    image: izdrail/publicsos.ro:main
    container_name: publicsos.ro
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '1700:1600'
      - '1701:1601'
      - '1702:1602'
    environment:
      WWWUSER: '${WWWUSER}'
      WWWGROUP: '${WWWGROUP}'
      LARAVEL_SAIL: 1
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
    volumes:
      - './application-domain/php/:/var/www/php'
      - './application-domain/php/:/var/www/python'
    networks:
      - sail

  mysql:
    image: mysql:8.0
    container_name: mysql.publicsos.ro
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword  # Change this to a secure password
      MYSQL_DATABASE: laravelmail
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravelpassword  # Change this to a secure password
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - sail

volumes:
  mysql_data:

networks:
  sail:
    driver: bridge
