services:
  publicsos.org:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WWWUSER: '${WWWUSER:-1000}'
        WWWGROUP: '${WWWGROUP:-1000}'
    image: izdrail/publicsos.org:dev
    container_name: publicsos.org
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '1120:1120'
      - '1121:1121'
      - '1122:1122'
    environment:
      WWWUSER: '${WWWUSER}'
      WWWGROUP: '${WWWGROUP}'
      LARAVEL_SAIL: 1
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
    volumes:
      - './application-domain/php/:/var/www/php'
      - './application-domain/python/:/var/www/python'
    networks:
      - sail

  mysql:
    image: mysql:8.0
    container_name: developer.publicsos.org
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword  # Change this to a secure password
      MYSQL_DATABASE: laravelmail
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravelpassword  # Change this to a secure password
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - sail

volumes:
  mysql_data:

networks:
  sail:
    driver: bridge
