[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

# CRM
[program:crm]
command=php -d variables_order=EGPCS /var/www/php/artisan octane:start --watch --server=roadrunner --host=0.0.0.0 --port=1120 --log=debug
autorestart=true
startsecs=5
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0




# Laravel Scheduler (No Port)
[program:laravel-scheduler]
process_name=%(program_name)s_%(process_num)02d
command=php artisan schedule:work
directory=/var/www/php/
autostart=true
autorestart=true
killasgroup=true
stopasgroup=true
numprocs=1
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0


# Laravel Horizon (No Port)
[program:laravel-horizon]
process_name=%(program_name)s_%(process_num)02d
command=php artisan horizon
directory=/var/www/php/
autostart=true
autorestart=true
killasgroup=true
stopasgroup=true
numprocs=1
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0


# Laravel REVERB (No Port)
[program:laravel-reverb]
process_name=%(program_name)s_%(process_num)02d
command=php artisan reverb:start
directory=/var/www/php/
autostart=true
autorestart=true
killasgroup=true
stopasgroup=true
numprocs=1
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0



# REDIS
[program:redis-server]
command=redis-server
autostart=true
autorestart=true
startsecs=5
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
