[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

# Port 13000 (Laravel)
[program:laravel-runner]
command=php -d variables_order=EGPCS /var/www/artisan octane:start --watch --server=roadrunner --host=0.0.0.0 --port=1600 --rpc-port=1601
autorestart=true
startsecs=5
redirect_stderr=true
stdout_logfile=/var/www/storage/logs/laravel.log
stdout_logfile_maxbytes=0
stderr_logfile=/var/www/storage/logs/laravel.log
stderr_logfile_maxbytes=0


# Redis Servicer (Port 6379)
[program:redis-server]
command=redis-server
autostart=true
autorestart=true
startsecs=5
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
